export const customersList = [
  {"nomClient": "AAMOUSA MAJIDE", "adresse": "ATTATBA", "telephone": "0561835936", "region": "BLIDA"},
  {"nomClient": "ABADOU ISMAIL", "adresse": "DOUAOUDA", "telephone": "0663353139", "region": ""},
  {"nomClient": "ABDECHAFI MESSAOUI VENT", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ABDEGHANI SOUMAA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ABDEKADER FODIL", "adresse": "FOUKA", "telephone": "0661832237", "region": ""},
  {"nomClient": "ABDELADER MOHAMMED", "adresse": "AACHOUR", "telephone": "", "region": ""},
  {"nomClient": "ABDELKADER BABOU", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ABDELKADER NEGHLI", "adresse": "CHLEF", "telephone": "0773962429-0671537104", "region": "Chlef"},
  {"nomClient": "ABDENNOUR KBAILI", "adresse": "MEFTAH", "telephone": "0795578720", "region": ""},
  {"nomClient": "ABDERRAHMEN ZAOUI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ABDESSAMED GUICHENITI", "adresse": "OULED SLAMA", "telephone": "0668176265", "region": ""},
  {"nomClient": "ABESS OULED MOUSSA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ADEL OUCHAH", "adresse": "OUDE OULEG", "telephone": "0774209490", "region": "BLIDA"},
  {"nomClient": "AHMED HAMZA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "AKRAM BAITI", "adresse": "FOUKA", "telephone": "0669713500", "region": "ALGER"},
  {"nomClient": "ALI ABOU REKIA", "adresse": "FOUKA", "telephone": "0669713500", "region": ""},
  {"nomClient": "AMI RACHIDE KHAZNA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "AMIRAT CHERCHEL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "AYOUB BELABBAS", "adresse": "BOUISMAIM", "telephone": "0771422765", "region": ""},
  {"nomClient": "AYOUBE KHEDIME", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "AZIOUAZ DRARIA", "adresse": "DRARIA", "telephone": "", "region": ""},
  {"nomClient": "AZLAGI YACINE", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "AZZEDINE BOUCHOUL", "adresse": "EL OUED", "telephone": "0663.85.41.32", "region": "El Oued"},
  {"nomClient": "BARAKA SILMEN", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "BARKAT KMIS", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "BAZIZ CHERCHEL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "BELKHIR OUSSAMA", "adresse": "OULED HADADJ", "telephone": "0549084282", "region": ""},
  {"nomClient": "BENALIA BELKACEM", "adresse": "HAMMADI", "telephone": "0550215920", "region": ""},
  {"nomClient": "BENALIA BOUBAKER", "adresse": "HAMMADI", "telephone": "0540402549", "region": ""},
  {"nomClient": "BENAMAR AIMEN HANOUT", "adresse": "SAOULA", "telephone": "0563030721", "region": ""},
  {"nomClient": "BENAMAR HATEM", "adresse": "ROUTE DE DRARIA N 06 RDC SAOULA ALGER", "telephone": "0541731840", "region": "Alger"},
  {"nomClient": "BENAMAR YACINE", "adresse": "SAOULA", "telephone": "", "region": ""},
  {"nomClient": "BILAL CHATAB", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "BILAL SIDIRACHED", "adresse": "SIDI RACHED", "telephone": "0663328951", "region": ""},
  {"nomClient": "BOUDEBIA MOHAMMED", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "BOUROUBA LAKHDAR", "adresse": "FOUKA", "telephone": "0772032408", "region": ""},
  {"nomClient": "CHERIFI DJILALI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "CHETTOUH MUSTAPHA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "CHOUIKHI HAMZA", "adresse": "SIDI MOUSSA", "telephone": "", "region": ""},
  {"nomClient": "DAHMAN OULED MOUSSA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "DJAMEL MECANSIAN", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "FAISSAL KARKOUCHE", "adresse": "", "telephone": "", "region": "BLIDA"},
  {"nomClient": "FARES HAMZAOUI", "adresse": "BENI MERAD", "telephone": "0550994311", "region": ""},
  {"nomClient": "FAROUK", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "FAYCAL REZIG", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "FERTAS ABDELKARIM", "adresse": "BOUINAN", "telephone": "", "region": ""},
  {"nomClient": "FERTAS AISSA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "FERTAS KARIM", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "FOUAD SIAKHEN", "adresse": "MEFTAH", "telephone": "", "region": ""},
  {"nomClient": "GARA MOHAMMED SAMIR", "adresse": "TELEMSAN", "telephone": "0552.59.90.35", "region": ""},
  {"nomClient": "GEUNDOUZ ZAKARIA", "adresse": "KHODAM", "telephone": "", "region": ""},
  {"nomClient": "HAKIM CHABA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HALIM BOUTALBI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HALIM GOTTACHE", "adresse": "KHEMIS EL KHACHNA", "telephone": "0771.12.51.23", "region": ""},
  {"nomClient": "HAMID OUAIL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HAMID ZERALDA", "adresse": "ZERALDA", "telephone": "0553.36.76.65", "region": ""},
  {"nomClient": "HAMZA GARGOUT", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HAMZA IBRAHIM", "adresse": "OULED FAYET", "telephone": "", "region": ""},
  {"nomClient": "HAMZA NOUREDDINE", "adresse": "OULED FAIT", "telephone": "", "region": ""},
  {"nomClient": "HAMZA OUNNAR", "adresse": "CHELF", "telephone": "", "region": ""},
  {"nomClient": "HASSNAOUI OMAR", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HICHEM KEDAM", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HOCINE FERRAH", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "HOUSSEM CHABOU", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "IHAB", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ISMAIL MEFTAH", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "KALACHE HAMID", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "KANOUN TAHER", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "KAROUM YOUNES", "adresse": "HLAIMIA BOUDOUAOU", "telephone": "0666689880", "region": ""},
  {"nomClient": "KEBICH MOHAMMED", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "KHACEMI MOHAMMED", "adresse": "CHERCHEL", "telephone": "0665307212", "region": "TIPAZA"},
  {"nomClient": "KHALED BOUZENOUNE", "adresse": "OULED YAICH", "telephone": "0551347097", "region": ""},
  {"nomClient": "KHSARA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "LAMRI LAZHAR", "adresse": "OULED SLAMA", "telephone": "0699085885", "region": ""},
  {"nomClient": "LAZOURI NABIL", "adresse": "DERARIA", "telephone": "", "region": ""},
  {"nomClient": "LITAT HILAL", "adresse": "DRARIA", "telephone": "0782825903", "region": ""},
  {"nomClient": "LOTFI BARKATI", "adresse": "KASER BOUKHARI", "telephone": "0795.07.97.92", "region": ""},
  {"nomClient": "MAAMER HAMIDA", "adresse": "DOUAOUDA", "telephone": "0555792793", "region": ""},
  {"nomClient": "MADJID HAJOUT", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MAKI SALIM", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MAZIZ SAMIR", "adresse": "GARGOUR", "telephone": "0783181917", "region": ""},
  {"nomClient": "MEDJADJI MOHAMMED", "adresse": "KOLÉA", "telephone": "0676253504", "region": ""},
  {"nomClient": "MEHDAOUI LAKHDAR", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MELIHI MOHAMMED", "adresse": "OUED FODDA", "telephone": "0540921726", "region": "Chlef"},
  {"nomClient": "MEZIANI SALAH", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MEZLIOUI ABDELHAK", "adresse": "", "telephone": "0540645735", "region": ""},
  {"nomClient": "MEZZAH DJAMEL", "adresse": "MEFTAH", "telephone": "", "region": ""},
  {"nomClient": "MEZZAH MOHAMMED", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MOHAMMED BEN AMAR", "adresse": "BARAKI", "telephone": "0542.95.39.08", "region": ""},
  {"nomClient": "MOHAMMED BOUZANOUN", "adresse": "", "telephone": "0550.28.74.32", "region": ""},
  {"nomClient": "MOKHTAR BOUIALI", "adresse": "AACHOUR", "telephone": "0557.12.83.27", "region": ""},
  {"nomClient": "MOKHTARI SALEM", "adresse": "FOUKA TIBAZA", "telephone": "0775262049/0675093521", "region": ""},
  {"nomClient": "MOUNIR BOUSMAIL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "MOURAD AIN BENAIN", "adresse": "AIN BENAIN", "telephone": "0550598715", "region": ""},
  {"nomClient": "NOUREDDIN HAMZA", "adresse": "OULED FAYET", "telephone": "", "region": ""},
  {"nomClient": "OMAR KARROUM", "adresse": "GRARA GHARDAIA", "telephone": "0697953737", "region": "Ghardaia"},
  {"nomClient": "OUALI FATHI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "OULD MAHIEDDINE ABDELHAFID", "adresse": "CHEBLI", "telephone": "0698370096", "region": ""},
  {"nomClient": "REHOUMA BELKASSEM", "adresse": "SOUIDANIA", "telephone": "0552511701", "region": ""},
  {"nomClient": "REMDANI HAKIM", "adresse": "KAHWAT CHARKI", "telephone": "", "region": ""},
  {"nomClient": "REMDANI SOUFAIN", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "RIAD BENSADGUA", "adresse": "MEDIA", "telephone": "0792.52.28.79", "region": ""},
  {"nomClient": "RIAD BENSADGUA 2", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ROJI KHEMIS MILIANA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "SALIM SOUMAA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "SALMA NOURDIN", "adresse": "MEFTAH", "telephone": "", "region": ""},
  {"nomClient": "SAMIR OULEDSLMA", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "SAYEH ABDELAZIZ", "adresse": "FOUKA", "telephone": "", "region": ""},
  {"nomClient": "SEDRATI AHMED", "adresse": "DOUIRA", "telephone": "", "region": ""},
  {"nomClient": "SIAKENE AMINE", "adresse": "LARBAA BLIDA", "telephone": "0540058901", "region": "Blida"},
  {"nomClient": "SIDI ALI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "SIDI HMED ZABOUJ", "adresse": "CHLEF", "telephone": "0659750192", "region": "Chlef"},
  {"nomClient": "SIRELA MOHAMMED", "adresse": "MEFTAH", "telephone": "0540603779", "region": ""},
  {"nomClient": "SOUFAIN BOURGIGA", "adresse": "BOURGIGA", "telephone": "0672328210", "region": ""},
  {"nomClient": "TEGGER ALA", "adresse": "CHELEF", "telephone": "0559147045", "region": ""},
  {"nomClient": "TEMBER ABDELAH", "adresse": "ROUINA CHELEF", "telephone": "", "region": ""},
  {"nomClient": "TOUFIK", "adresse": "DRAIRIA", "telephone": "", "region": ""},
  {"nomClient": "TOUFIK SENADJKI", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "VENTE COMPTOIR", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "WALID DEBAGH", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "WALID EL ATTAF", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "WALID KALITOUS", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "WALID KHENNOUCHE", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YACINE FARHAT", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YACINE SOUIKI SOLTAN", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YAHIA BOUKHERS", "adresse": "", "telephone": "0550.95.81.48", "region": ""},
  {"nomClient": "YAKHLEF ABDEKADDER", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YASSER DERBAL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YEZLI MOHAMMED LAMINE", "adresse": "BOUSMAIL", "telephone": "", "region": ""},
  {"nomClient": "YOUCEF BOUSMAIL", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "YOUCEF CHELEF", "adresse": "", "telephone": "", "region": ""},
  {"nomClient": "ZINOU FERRAH", "adresse": "HAMADI", "telephone": "", "region": ""},
  {"nomClient": "ZIOUCHE MOHAMMED", "adresse": "KHMIS MILINA", "telephone": "0778879770", "region": "AIN DEFLA"},
  {"nomClient": "ZMIT SALIM", "adresse": "ERBAA", "telephone": "0770929621", "region": ""},
  {"nomClient": "ZOURGUI MOHAMED", "adresse": "", "telephone": "", "region": ""}
];